config/routes.rb
EventCheckin::Application.routes.draw do
  resources :tables

  resources :restaurants

  resources :bookings do
    collection do
      get 'make_booking'
      get 'find_booking_data'
      get 'checkin'
    end
  end

  devise_scope :user do
    match "/users/sign_out" => "sessions#destroy"
    match 'sign_up' => "registrations#new"
  end
  devise_for :users, :controllers => {:registrations =>"registrations", :sessions => "sessions" }
  match "users/user_profile" => "users#user_profile"

  root :to => 'home#index'
  resources :home
  resources :home1
  resource  :sessions

end

app/models/booking.rb
class Booking < ActiveRecord::Base
  belongs_to :restaurant
  belongs_to :user
  belongs_to :table
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  # GET /bookings
  # GET /bookings.json
  protect_from_forgery :except => [:create,:find_booking_data]
  def index
    restaurant = Restaurant.find_by_id(params[:restaurant_id])
    @bookings = restaurant.bookings
   render :json=> @bookings

  end

  # GET /bookings/1
  # GET /bookings/1.json
  def show
    @booking = Booking.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @booking }
    end
  end

  # GET /bookings/new
  # GET /bookings/new.json
  def new
    @booking = Booking.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @booking }
    end
  end

  # GET /bookings/1/edit
  def edit
    @booking = Booking.find(params[:id])
  end

  # POST /bookings
  # POST /bookings.json
  def create
    #debugger
    @booking = Booking.new(params[:booking])
    @booking.table_id= params[:table_id]
    @booking.restaurant_id = params[:restaurant_id]
    @booking.guests = params[:guests]
    @booking.user_id = current_user.id if current_user
    time = params[:b_time]
    hour= time.split(":")[0]
    min= time.split(":")[1]
    date1 = params[:date]
    year= date1.split("/")[2]
    month = date1.split("/")[1]
    day = date1.split("/")[0]
    date_time= Time.utc(year,month,day,hour,min)
    @booking.start_time = date_time
    @booking.end_time = date_time+2.hours
    respond_to do |format|
      if @booking.save
        format.html { redirect_to @booking, notice: 'Booking was successfully created.' }
        format.json { render json: @booking, status: :created, location: @booking }
      else
        format.html { render action: "new" }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bookings/1
  # PUT /bookings/1.json
  def update
    @booking = Booking.find(params[:id])

    respond_to do |format|
      if @booking.update_attributes(params[:booking])
        format.html { redirect_to @booking, notice: 'Booking was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @booking.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bookings/1
  # DELETE /bookings/1.json
  def destroy
    @booking = Booking.find(params[:id])
    @booking.destroy

    respond_to do |format|
      format.html { redirect_to bookings_url }
      format.json { head :ok }
    end
  end
  def make_booking
    @restaurants = Restaurant.all
  end
  def find_booking_data
    #debugger
    guests= params[:guests]
    date = params[:date]
    restaurant_id = params[:restaurant_id]
    time = params[:time]
    restaurant = Restaurant.find_by_id(restaurant_id)
    @tables = restaurant.tables.where("max_covers> ?",guests)
    render :json =>@tables
  end
  def checkin
    @restaurants = Restaurant.all

  end
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/views/bookings/_form.html.erb
<%= form_for(@booking) do |f| %>
  <% if @booking.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@booking.errors.count, "error") %> prohibited this booking from being saved:</h2>

      <ul>
      <% @booking.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :guests %><br />
    <%= f.number_field :guests %>
  </div>
  <div class="field">
    <%= f.label :start_time %><br />
    <%= f.datetime_select :start_time %>
  </div>
  <div class="field">
    <%= f.label :end_time %><br />
    <%= f.datetime_select :end_time %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :restaurant_id %><br />
    <%= f.number_field :restaurant_id %>
  </div>
  <div class="field">
    <%= f.label :notes %><br />
    <%= f.text_area :notes %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bookings/checkin.html.haml
!!!
%html{:xmlns => "http://www.w3.org/1999/xhtml"}
  %head
    %title PeopleCheck::Booking
    %meta{:content => "text/html; charset=utf-8", "http-equiv" => "Content-Type"}/
  %body
    .conteanier_home
      .all_header_box
        .header_home
          .fl
            %a{:href => "/home1"}
              %img{:alt => "image", :border => "0", :src => "/assets/small_logo.png"}/
          .dashed_text_box
            .dashed_text
              %a{:href => "#."} Dashboard
            .dashed_text2
              %a{:href => "#."} Apps
            .dashed_text3
              %a{:href => "#."} I want this !
            .clr
          .header_field_box
            %input.header_field_size{:placeholder => "Search", :type => "text"}/
          .checkin_box
            .checkin_box_text
              %a{:href => "/bookings/make_booking"} Booking
            .checkin_box_text
              %a{:href => "/users/user_profile"} Profile
            .checkin_box_text
              %a{:href => "/bookings/checkin"} CheckIn
            .checkin_box_text
              %a{:href => "#."} Setting
            .clr
          .refresh_row
            .refresh_box
              .fl
                %a{:href => "#."}
                  %img{:alt => "image", :border => "0", :src => "/assets/refresh.png"}/
              .refresh_text
                %a{:href => "#."} Reset
              .clr
            .refresh_box
              .fl
                %a{:href => "#."}
                  %img{:alt => "image", :border => "0", :src => "/assets/theme.png"}/
              .refresh_text2
                %a{:href => "#."} Theme
              .clr
            .refresh_box
              .fl
                %a{:href => "#."}
                  %img{:alt => "image", :border => "0", :src => "/assets/logout.png"}/
              .refresh_text
                %a{:href => "#."} Logout
              .clr
            .clr
          .clr
      .body_wrepper_profile
        .john_name_box
          .john_name John Stephen
          .fl
            %a{:href => "#."}
              %img{:alt => "image", :border => "0", :src => "/assets/john.png"}/
          .clr
        .clr
        .booking_body
          .make_booking

            //= form_tag("/bookings")
            .dfdf
              .make_booking_text Select Restaurant to search bookings
              .make_button
                %a{:href => "#."}
                  %img{:alt => "image", :border => "0", :src => "/assets/name_button.png"}/
              %div
                %select{:class=>"make_drop_down_size", :id=>"restaurant_id", :name => "restaurants[restaurant_id]", :prompt => 'Select a restaurant'}
                  = options_from_collection_for_select @restaurants, :id, :name
              .find_table_row

                .fl
                  %a{:href => "#.",:class=>"find_booking_btn"}
                    %img{:alt => "image", :border => "0", :src => "/assets/find_bookings.png"}/
                .clr
          .find_booking_table
            .booking_confirm.hidden
              You have successfully checkedIn for this booking.
            %table{:border => "0", :cellpadding => "0", :cellspacing => "0"}
              %tbody.hidden{:class=>"table1"}
                %tr
                  %th.find_booking_table_heading Start Time
                  %th.find_booking_table_heading_2 End Time
                  %th.find_booking_table_heading_2 Guests
                  %th.find_booking_table_heading_3 Customer Name
                  %th.find_booking_table_heading_4 CheckIn ( Click to checkIn )
                %tr
                  %td Corner Table
                  %td Table 1
                  %td Min : 2 - Max : 5
                  %td $10
                  %td
                    .time_cafe_box
                      .cafe_green_box
                        %a{:href => "#."} 14:00
                      .clr
      .all_footer
        .footer
          %div
            %img{:alt => "image", :border => "0", :src => "/assets/BORDER_TOP.png"}/
          .footer_text_box_new
            .footer_text
              %a{:href => "#."} Terms of Service
            .footer_text_new
              |
            .footer_text
              %a{:href => "#."} Privacy Policy
            .footer_text_new
              |
            .footer_text
              %a{:href => "#."} Support
            .footer_text_new
              |
            .footer_text
              %a{:href => "#."} Contact Us
            .clr
          %div
            %img{:alt => "image", :border => "0", :src => "/assets/BORDER_TOP.png"}/
:javascript

  $(document).ready(function(){
    $(".chzn-select").chosen(); $(".chzn-select-deselect").chosen({allow_single_deselect:true});
    $('.find_table_drop_size1').click(function(event){$('#ui-datepicker-div').css('z-index','30');});
    $('.find_table_drop_size1').datepicker({
       dateFormat: "dd/mm/yy",
       onSelect: function(dateText, inst){
         selDate = dateText;

         }
    });

    $(".find_booking_btn").click(function(event){
      res_id = $("#restaurant_id").val();
          $(".booking_confirm").hide();
      //date= $(".find_table_drop_size1").val();
      //time = $("#time_slots").val();
      //guests = $("#covers").val();
      $.get("/bookings?restaurant_id="+res_id,function(data){
        $(".table1").html("");
        $(".table1").html('<tr><th class="find_booking_table_heading">Date</th><th class="find_booking_table_heading">Start Time</th><th class="find_booking_table_heading_2">End Time</th><th class="find_booking_table_heading_2">Guests</th><th class="find_booking_table_heading_3">Customer Name</th><th class="find_booking_table_heading_4">CheckIn ( Click to CheckIn)</th></tr>');
        tables = data;
        if(tables.length>0)
        {
          for(var i=0;i<tables.length;i++)
          {
           console.log(i);

            div="";
            s_date = tables[i].start_time.split("T")[0];
            s_time = tables[i].start_time.split("T")[1];
            e_date = tables[i].end_time.split("T")[0];
            e_time = tables[i].end_time.split("T")[1];

            div="<tr table_id="+tables[i].id+"><td>"+s_date+"</td><td>"+s_time+"</td><td>"+e_time+"</td><td>"+tables[i].guests+"</td><td>Rashed</td><td><div class='time_cafe_box'><a href='#.' class='checkin_button'>CheckIn</a><div class='clr'></div></div> </td></tr>";
             $(".table1").append(div);
          }
        }
        else{
          div='<tr><td colspan="6">No Booking found for given restaurant.</td></tr>;'
          $(".table1").append(div);
        }
        $(".table1").show();
        confirm_booking();

      });
      event.preventDefault();
      return false;
    });
    function confirm_booking()
    {
      $(".checkin_button").unbind("click");
      $(".checkin_button").click(function(event){
      if(confirm("Are you sure, you want to checkIn for this booking ?"))
      {

          $(".table1").hide();
          $(".booking_confirm").show();
      }
      event.preventDefault();
      return false;
      });
    }
  });

app/views/bookings/edit.html.erb
<h1>Editing booking</h1>

<%= render 'form' %>

<%= link_to 'Show', @booking %> |
<%= link_to 'Back', bookings_path %>

app/views/bookings/index.html.erb
<h1>Listing bookings</h1>

<table>
  <tr>
    <th>Guests</th>
    <th>Start time</th>
    <th>End time</th>
    <th>User</th>
    <th>Restaurant</th>
    <th>Notes</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @bookings.each do |booking| %>
  <tr>
    <td><%= booking.guests %></td>
    <td><%= booking.start_time %></td>
    <td><%= booking.end_time %></td>
    <td><%= booking.user_id %></td>
    <td><%= booking.restaurant_id %></td>
    <td><%= booking.notes %></td>
    <td><%= link_to 'Show', booking %></td>
    <td><%= link_to 'Edit', edit_booking_path(booking) %></td>
    <td><%= link_to 'Destroy', booking, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Booking', new_booking_path %>

app/views/bookings/make_booking.html.haml
!!!
%html{:xmlns => "http://www.w3.org/1999/xhtml"}
  %head
    %title PeopleCheck::Booking
    %meta{:content => "text/html; charset=utf-8", "http-equiv" => "Content-Type"}/
  %body
    .conteanier_home
      .all_header_box
        .header_home
          .fl
            %a{:href => "/home1"}
              %img{:alt => "image", :border => "0", :src => "/assets/small_logo.png"}/
          .dashed_text_box
            .dashed_text
              %a{:href => "#."} Dashboard
            .dashed_text2
              %a{:href => "#."} Apps
            .dashed_text3
              %a{:href => "#."} I want this !
            .clr
          .header_field_box
            %input.header_field_size{:placeholder => "Search", :type => "text"}/
          .checkin_box
            .checkin_box_text
              %a{:href => "/bookings/make_booking"} Booking
            .checkin_box_text
              %a{:href => "/users/user_profile"} Profile
            .checkin_box_text
              %a{:href => "/bookings/checkin"} CheckIn
            .checkin_box_text
              %a{:href => "#."} Setting
            .clr
          .refresh_row
            .refresh_box
              .fl
                %a{:href => "#."}
                  %img{:alt => "image", :border => "0", :src => "/assets/refresh.png"}/
              .refresh_text
                %a{:href => "#."} Reset
              .clr
            .refresh_box
              .fl
                %a{:href => "#."}
                  %img{:alt => "image", :border => "0", :src => "/assets/theme.png"}/
              .refresh_text2
                %a{:href => "#."} Theme
              .clr
            .refresh_box
              .fl
                %a{:href => "#."}
                  %img{:alt => "image", :border => "0", :src => "/assets/logout.png"}/
              .refresh_text
                %a{:href => "#."} Logout
              .clr
            .clr
          .clr
      .body_wrepper_profile
        .john_name_box
          .john_name John Stephen
          .fl
            %a{:href => "#."}
              %img{:alt => "image", :border => "0", :src => "/assets/john.png"}/
          .clr
        .clr
        .booking_body
          .make_booking

            //= form_tag("/bookings")
            .dfdf
              .make_booking_text Make a  Restaurant Booking
              .make_button
                %a{:href => "#."}
                  %img{:alt => "image", :border => "0", :src => "/assets/name_button.png"}/
              %div
                %select{:class=>"make_drop_down_size", :id=>"restaurant_id", :name => "restaurants[restaurant_id]", :prompt => 'Select a restaurant'}
                  = options_from_collection_for_select @restaurants, :id, :name
              .find_table_row
                .find_table_box
                  .find_table_image
                    %a{:href => "#."}
                      %img{:alt => "image", :border => "0", :src => "/assets/clender_new.png"}/
                  .fl
                    %input.find_table_drop_size1

                  .clr
                .find_table_box
                  .find_table_image
                    %a{:href => "#."}
                      %img{:alt => "image", :border => "0", :src => "/assets/clock.png"}/
                  .fl
                    %select.find_table_drop_size#time_slots
                      %option{:value => "00:00"} 00:00
                      %option{:value => "00:30"} 00:30
                      %option{:value => "01:00"} 01:00
                      %option{:value => "01:30"} 01:30
                      %option{:value => "2:00"} 2:00
                      %option{:value => "2:30"} 2:30
                      %option{:value => "3:00"} 3:00
                      %option{:value => "3:30 "} 3:30
                      %option{:value => "4:00 "} 4:00
                      %option{:value => "4:30"} 4:30
                      %option{:value => "5:00"} 5:00
                      %option{:value => "5:30"} 5:30
                      %option{:value => "6:00"} 6:00
                      %option{:value => "6:30"} 6:30
                      %option{:value => "7:00"} 7:00
                      %option{:value => "7:30"} 7:30
                      %option{:value => "8:00"} 8:00
                      %option{:value => "8:30"} 8:30
                      %option{:value => "9:00"} 9:00
                      %option{:value => "9:30"} 9:30
                      %option{:value => "10:00"} 10:00
                      %option{:value => "10:30"} 10:30
                      %option{:value => "11:00"} 11:00
                      %option{:value => "11:30"} 11:30
                      %option{:value => "12:00"} 12:00
                      %option{:value => "12:30"} 12:30
                      %option{:value => "13:00"} 13:00
                      %option{:value => "13:30"} 13:30
                      %option{:value => "14:00"} 14:00
                      %option{:value => "14:30"} 14:30
                      %option{:value => "15:00"} 15:00
                      %option{:value => "15:30"} 15:30
                      %option{:value => "16:00"} 16:00
                      %option{:value => "16:30"} 16:30
                      %option{:value => "17:00"} 17:00
                      %option{:value => "17:30"} 17:30
                      %option{:value => "18:00"} 18:00
                      %option{:value => "18:30"} 18:30
                      %option{:value => "19:00"} 19:00
                      %option{:value => "19:30"} 19:30
                      %option{:value => "20:00"} 20:00
                      %option{:value => "20:30"} 20:30
                      %option{:value => "21:00"} 21:00
                      %option{:value => "21:30"} 21:30
                      %option{:value => "22:00"} 22:00
                      %option{:value => "22:30"} 22:30
                      %option{:value => "23:00"} 23:00
                      %option{:value => "23:30"} 23:30


                  .clr
                .find_table_box
                  .find_table_image
                    %a{:href => "#."}
                      %img{:alt => "image", :border => "0", :src => "/assets/people.png"}/
                  .fl
                    %select.find_table_drop_size#covers
                      %option{:value => "1"} 1 person
                      %option{:selected => "selected", :value => "2"} 2 people
                      %option{:value => "3"} 3 people
                      %option{:value => "4"} 4 people
                      %option{:value => "5"} 5 people
                      %option{:value => "6"} 6 people
                      %option{:value => "7"} 7 people
                      %option{:value => "8"} 8 people
                      %option{:value => "9"} 9 people
                      %option{:value => "10"} 10 people
                      %option{:value => "11"} 11 people
                      %option{:value => "12"} 12 people
                      %option{:value => "13"} 13 people
                      %option{:value => "14"} 14 people
                      %option{:value => "15"} 15 people
                      %option{:value => "16"} 16 people
                      %option{:value => "17"} 17 people
                      %option{:value => "18"} 18 people
                      %option{:value => "19"} 19 people
                      %option{:value => "20"} 20 people
                      %option{:value => "21"} Larger Party
                  .clr
                .fl
                  %a{:href => "#.",:class=>"find_booking_btn"}
                    %img{:alt => "image", :border => "0", :src => "/assets/find_button.png"}/
                .clr
          .find_booking_table
            .booking_confirm.hidden
              A booking has been confirmed for the given date and time.
            %table{:border => "0", :cellpadding => "0", :cellspacing => "0"}
              %tbody.hidden{:class=>"table1"}
                %tr
                  %th.find_booking_table_heading Table Name
                  %th.find_booking_table_heading_2 Table Number
                  %th.find_booking_table_heading_2 Capacity
                  %th.find_booking_table_heading_3 Price
                  %th.find_booking_table_heading_4 Availability ( Click time to reserve )
                %tr
                  %td Corner Table
                  %td Table 1
                  %td Min : 2 - Max : 5
                  %td $10
                  %td
                    .time_cafe_box
                      .cafe_green_box_active 12:00
                      .cafe_green_box
                        %a{:href => "#."} 12:30
                      .cafe_green_box
                        %a{:href => "#."} 13:00
                      .cafe_green_box
                        %a{:href => "#."} 13:30
                      .cafe_green_box
                        %a{:href => "#."} 14:00
                      .clr
      .all_footer
        .footer
          %div
            %img{:alt => "image", :border => "0", :src => "/assets/BORDER_TOP.png"}/
          .footer_text_box_new
            .footer_text
              %a{:href => "#."} Terms of Service
            .footer_text_new
              |
            .footer_text
              %a{:href => "#."} Privacy Policy
            .footer_text_new
              |
            .footer_text
              %a{:href => "#."} Support
            .footer_text_new
              |
            .footer_text
              %a{:href => "#."} Contact Us
            .clr
          %div
            %img{:alt => "image", :border => "0", :src => "/assets/BORDER_TOP.png"}/
:javascript

  $(document).ready(function(){
    $(".chzn-select").chosen(); $(".chzn-select-deselect").chosen({allow_single_deselect:true});
    $('.find_table_drop_size1').click(function(event){$('#ui-datepicker-div').css('z-index','30');});
    $('.find_table_drop_size1').datepicker({
       dateFormat: "dd/mm/yy",
       onSelect: function(dateText, inst){
         selDate = dateText;

         }
    });

    $(".find_booking_btn").click(function(event){
      res_id = $("#restaurant_id").val();
      $(".booking_confirm").hide();
      date= $(".find_table_drop_size1").val();
      time = $("#time_slots").val();
      guests = $("#covers").val();
      $.get("/bookings/find_booking_data?time="+time+"&guests="+guests+"&date="+date+"&restaurant_id="+res_id,function(data){
        $(".table1").html("");
        $(".table1").html('<tr><th class="find_booking_table_heading">Table Name</th><th class="find_booking_table_heading_2">Table Number</th><th class="find_booking_table_heading_2">Capacity</th><th class="find_booking_table_heading_3">Price</th><th class="find_booking_table_heading_4">Availability ( Click time to reserve )</th></tr>');
        tables = data;
        if(tables.length>0)
        {
          for(var i=0;i<tables.length;i++)
          {
           console.log(i);

            div="";
            div="<tr table_id="+tables[i].id+"><td>"+tables[i].table_name+"</td><td>Table"+tables[i].table_no+"</td><td>Min : "+tables[i].min_covers+" - Max : "+tables[i].max_covers+"</td><td>$10</td><td><div class='time_cafe_box'><div class='cafe_green_box_active'>12:00</div><div class='cafe_green_box'><a href='#.'>12:30</a></div><div class='cafe_green_box'><a href='#.'>13:00</a></div><div class='cafe_green_box'><a href='#.'>13:30</a></div><div class='clr'></div></div> </td></tr>";
             $(".table1").append(div);
          }
        }
        else{
          div='<tr><td colspan="5">No table found for given guests and time. Please try other.</td></tr>;'
          $(".table1").append(div);
        }
        $(".table1").show();
        confirm_booking();

      });
      event.preventDefault();
      return false;
    });
    function confirm_booking()
    {
      $(".cafe_green_box").unbind("click");
      $(".cafe_green_box").click(function(event){
      if(confirm("Are you sure, you want to book this slot ?"))
      {
        b_time= $(this).text();
        res_id = $("#restaurant_id").val();
        date= $(".find_table_drop_size1").val();
        time = $("#time_slots").val();
        guests = $("#covers").val();
        table_id= $(this).parent().parent().parent().attr("table_id");
        $.post("/bookings?table_id="+table_id+"&b_time="+b_time+"&restaurant_id="+res_id+"&date="+date+"&guests="+guests,function(data){
          console.log(data);
          $(".table1").hide();
          $(".booking_confirm").show();
        });
      }
      event.preventDefault();
      return false;
      });
    }
  });

app/views/bookings/new.html.erb
<h1>New booking</h1>

<%= render 'form' %>

<%= link_to 'Back', bookings_path %>

app/views/bookings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Guests:</b>
  <%= @booking.guests %>
</p>

<p>
  <b>Start time:</b>
  <%= @booking.start_time %>
</p>

<p>
  <b>End time:</b>
  <%= @booking.end_time %>
</p>

<p>
  <b>User:</b>
  <%= @booking.user_id %>
</p>

<p>
  <b>Restaurant:</b>
  <%= @booking.restaurant_id %>
</p>

<p>
  <b>Notes:</b>
  <%= @booking.notes %>
</p>


<%= link_to 'Edit', edit_booking_path(@booking) %> |
<%= link_to 'Back', bookings_path %>