config/routes.rb
EventCheckin::Application.routes.draw do
  resources :tables

  resources :restaurants

  resources :bookings do
    collection do
      get 'make_booking'
      get 'find_booking_data'
      get 'checkin'
    end
  end

  devise_scope :user do
    match "/users/sign_out" => "sessions#destroy"
    match 'sign_up' => "registrations#new"
  end
  devise_for :users, :controllers => {:registrations =>"registrations", :sessions => "sessions" }
  match "users/user_profile" => "users#user_profile"

  root :to => 'home#index'
  resources :home
  resources :home1
  resource  :sessions

end

app/controllers/tables_controller.rb
class TablesController < ApplicationController
  # GET /tables
  # GET /tables.json
  def index
    @tables = Table.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tables }
    end
  end

  # GET /tables/1
  # GET /tables/1.json
  def show
    @table = Table.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @table }
    end
  end

  # GET /tables/new
  # GET /tables/new.json
  def new
    @table = Table.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @table }
    end
  end

  # GET /tables/1/edit
  def edit
    @table = Table.find(params[:id])
  end

  # POST /tables
  # POST /tables.json
  def create
    @table = Table.new(params[:table])

    respond_to do |format|
      if @table.save
        format.html { redirect_to @table, notice: 'Table was successfully created.' }
        format.json { render json: @table, status: :created, location: @table }
      else
        format.html { render action: "new" }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tables/1
  # PUT /tables/1.json
  def update
    @table = Table.find(params[:id])

    respond_to do |format|
      if @table.update_attributes(params[:table])
        format.html { redirect_to @table, notice: 'Table was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @table.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tables/1
  # DELETE /tables/1.json
  def destroy
    @table = Table.find(params[:id])
    @table.destroy

    respond_to do |format|
      format.html { redirect_to tables_url }
      format.json { head :ok }
    end
  end
end

app/helpers/tables_helper.rb
module TablesHelper
end

app/views/tables/_form.html.erb
<%= form_for(@table) do |f| %>
  <% if @table.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@table.errors.count, "error") %> prohibited this table from being saved:</h2>

      <ul>
      <% @table.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :covers %><br />
    <%= f.number_field :covers %>
  </div>
  <div class="field">
    <%= f.label :table_no %><br />
    <%= f.number_field :table_no %>
  </div>
  <div class="field">
    <%= f.label :table_name %><br />
    <%= f.text_field :table_name %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br />
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :restaurant_id %><br />
    <%= f.number_field :restaurant_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tables/edit.html.erb
<h1>Editing table</h1>

<%= render 'form' %>

<%= link_to 'Show', @table %> |
<%= link_to 'Back', tables_path %>

app/views/tables/index.html.erb
<h1>Listing tables</h1>

<table>
  <tr>
    <th>Covers</th>
    <th>Table no</th>
    <th>Table name</th>
    <th>User</th>
    <th>Restaurant</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tables.each do |table| %>
  <tr>
    <td><%= table.covers %></td>
    <td><%= table.table_no %></td>
    <td><%= table.table_name %></td>
    <td><%= table.user_id %></td>
    <td><%= table.restaurant_id %></td>
    <td><%= link_to 'Show', table %></td>
    <td><%= link_to 'Edit', edit_table_path(table) %></td>
    <td><%= link_to 'Destroy', table, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Table', new_table_path %>

app/views/tables/new.html.erb
<h1>New table</h1>

<%= render 'form' %>

<%= link_to 'Back', tables_path %>

app/views/tables/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Covers:</b>
  <%= @table.covers %>
</p>

<p>
  <b>Table no:</b>
  <%= @table.table_no %>
</p>

<p>
  <b>Table name:</b>
  <%= @table.table_name %>
</p>

<p>
  <b>User:</b>
  <%= @table.user_id %>
</p>

<p>
  <b>Restaurant:</b>
  <%= @table.restaurant_id %>
</p>


<%= link_to 'Edit', edit_table_path(@table) %> |
<%= link_to 'Back', tables_path %>